import type { Metadata } from 'next'
import { LegalDocumentLayout, LegalSection } from '@/components/legal/LegalDocumentLayout'

export const metadata: Metadata = { title: 'Termos de Uso | Prontusfy' }

export default function TermsOfUsePage() {
  return <LegalDocumentLayout eyebrow="Documento contratual" title="Termos de Uso">
    <LegalSection title="1. Aceitacao e escopo"><p>Estes Termos regulam o acesso e uso da plataforma Prontusfy. Ao criar uma conta, contratar um plano ou usar qualquer funcionalidade, voce declara que leu e aceitou estas condicoes.</p><p>O Prontusfy oferece ferramentas de gestao de clientes, agenda, comunicacao, relatorios e recursos relacionados. A contratacao comercial pode ter regras complementares apresentadas no checkout ou na proposta aplicavel.</p></LegalSection>
    <LegalSection title="2. Conta e responsabilidades do usuario"><p>O titular deve fornecer dados corretos, manter suas credenciais em sigilo e informar uso nao autorizado. Cada barbearia e responsavel pelas acoes realizadas em sua conta e pelos dados cadastrados por sua equipe.</p><p>O usuario deve utilizar a plataforma de forma legal, respeitosa e compativel com as regras aplicaveis ao WhatsApp, a LGPD e demais normas de protecao ao consumidor e dados pessoais.</p></LegalSection>
    <LegalSection title="3. Dados de clientes e comunicacoes"><p>O usuario e responsavel por possuir base legal, avisos e consentimentos necessarios para cadastrar contatos e enviar mensagens. O Prontusfy disponibiliza ferramentas; nao garante respostas, agendamentos ou resultados comerciais especificos.</p></LegalSection>
    <LegalSection title="4. Planos, pagamentos e cancelamento"><p>Planos pagos sao cobrados conforme a periodicidade selecionada. A renovacao automatica pode ser administrada na area de Assinatura quando disponivel. O cancelamento interrompe as renovacoes futuras, preservando o acesso ate o fim do periodo ja pago, salvo informacao diferente no checkout.</p><p>As regras de arrependimento e estorno estao descritas na <a className="font-semibold text-emerald-300 hover:text-emerald-200" href="/politica-de-reembolso">Politica de Reembolso</a>.</p></LegalSection>
    <LegalSection title="5. Suspensao e encerramento"><p>Podemos suspender ou limitar o acesso quando houver fraude, risco de seguranca, inadimplencia, uso abusivo, violacao destes Termos ou exigencia legal. Quando razoavelmente possivel, enviaremos aviso previo pelo canal cadastrado.</p></LegalSection>
    <LegalSection title="6. Propriedade intelectual e limitacao de responsabilidade"><p>A marca, software, interface, conteudos e tecnologias do Prontusfy pertencem aos seus titulares e nao podem ser copiados, revendidos ou explorados sem autorizacao. O servico e fornecido com medidas razoaveis de seguranca e continuidade, mas pode sofrer indisponibilidades, manutencoes ou integracoes de terceiros.</p><p>Na extensao permitida pela lei, o Prontusfy nao responde por perdas indiretas, lucros cessantes, dados inseridos incorretamente ou atos de terceiros. Nada nestes Termos reduz direitos que nao possam ser limitados pela legislacao aplicavel.</p></LegalSection>
    <LegalSection title="7. Alteracoes e contato"><p>Podemos atualizar estes Termos para refletir evolucoes legais ou do produto. A versao vigente permanecera publicada nesta pagina. Duvidas podem ser encaminhadas pelo Concierge dentro da plataforma.</p></LegalSection>
  </LegalDocumentLayout>
}