import type { Metadata } from 'next'
import { LegalDocumentLayout, LegalSection } from '@/components/legal/LegalDocumentLayout'

export const metadata: Metadata = { title: 'Politica de Privacidade | Prontusfy' }

const dpoEmail = process.env.NEXT_PUBLIC_DPO_EMAIL ?? 'privacidade@prontusfy.com'

export default function PrivacyPolicyPage() {
  return <LegalDocumentLayout eyebrow="LGPD e protecao de dados" title="Politica de Privacidade">
    <LegalSection title="1. Quem trata seus dados"><p>O Prontusfy atua como controlador dos dados da conta do lojista e como operador em nome da barbearia para dados de clientes, agenda e comunicacoes inseridos pelo usuario. A barbearia permanece responsavel pelas instrucoes e pela base legal dos dados de seus proprios clientes.</p></LegalSection>
    <LegalSection title="2. Dados coletados"><p>Podemos tratar dados de identificacao e contato, dados da barbearia, dados de autenticacao, preferencias, informacoes de clientes, agendamentos, servicos, pagamentos, registros de uso e dados tecnicos de seguranca.</p></LegalSection>
    <LegalSection title="3. Finalidades e bases legais"><p>Usamos os dados para criar e administrar contas, disponibilizar agenda e comunicacoes, processar pagamentos, prevenir fraude, atender solicitacoes, melhorar a plataforma e cumprir obrigacoes legais. O tratamento ocorre conforme execucao de contrato, cumprimento de obrigacao legal, legitimo interesse, consentimento ou outra base prevista na LGPD.</p></LegalSection>
    <LegalSection title="4. Armazenamento, seguranca e compartilhamento"><p>Os dados sao armazenados com controles tecnicos e administrativos razoaveis, incluindo infraestrutura e autenticacao do Supabase. Podemos compartilhar dados com provedores de hospedagem, autenticacao, pagamentos, analiticos e mensageria apenas na medida necessaria para operar o servico, sempre observando contratos e medidas de seguranca adequadas.</p><p>Nao vendemos dados pessoais. Transferencias internacionais, quando necessarias por provedores de infraestrutura, seguem mecanismos permitidos pela legislacao aplicavel.</p></LegalSection>
    <LegalSection title="5. Retencao e exclusao"><p>Conservamos dados pelo periodo necessario para as finalidades informadas, para defesa de direitos, seguranca e cumprimento de obrigacoes legais. O titular pode iniciar a exclusao da conta nas Configuracoes; dados cuja retencao seja obrigatoria poderao permanecer bloqueados pelo prazo legal.</p></LegalSection>
    <LegalSection title="6. Direitos do titular"><p>Nos termos da LGPD, voce pode pedir confirmacao de tratamento, acesso, correcao, anonimização, bloqueio, exclusao, portabilidade, informacao sobre compartilhamentos e revisao de decisoes automatizadas, quando aplicavel. Para dados de clientes da barbearia, o pedido deve ser direcionado primeiro a propria barbearia.</p></LegalSection>
    <LegalSection title="7. Cookies e contato do Encarregado"><p>Cookies essenciais mantem a sessao e a seguranca. Cookies analiticos e de marketing dependem do seu aceite. Consulte a <a className="font-semibold text-emerald-300 hover:text-emerald-200" href="/politica-de-cookies">Politica de Cookies</a> para detalhes.</p><p>Para exercer direitos ou falar com o Encarregado de Dados (DPO), envie uma solicitacao para <a className="font-semibold text-emerald-300 hover:text-emerald-200" href={`mailto:${dpoEmail}`}>{dpoEmail}</a>.</p></LegalSection>
  </LegalDocumentLayout>
}