import Link from 'next/link'
import BrandLogo from '@/components/BrandLogo'

export const metadata = { title: 'Politica de Privacidade | Prontusfy' }

export default function PrivacyPolicyPage() {
  return <main className="min-h-screen bg-slate-950 px-4 py-10 text-slate-200 sm:px-6"><article className="mx-auto max-w-3xl"><Link href="/" className="inline-flex"><BrandLogo markClassName="h-14 w-auto max-w-[200px]" /></Link><p className="mt-10 text-sm font-semibold uppercase tracking-[0.18em] text-emerald-400">Prontusfy</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-white">Politica de Privacidade</h1><p className="mt-4 text-sm text-slate-400">Ultima atualizacao: 26 de julho de 2026.</p><div className="mt-10 space-y-8 rounded-3xl border border-slate-800 bg-slate-900 p-6 leading-7 shadow-2xl sm:p-10"><Policy title="Dados que tratamos">Tratamos os dados informados no cadastro, dados da barbearia, clientes, agendamentos e configuracoes necessarias para entregar os recursos da plataforma.</Policy><Policy title="Finalidade">Usamos os dados para operar a conta, organizar clientes e agenda, enviar comunicacoes solicitadas, melhorar o produto e cumprir obrigacoes legais.</Policy><Policy title="Cookies">Cookies essenciais mantem sua sessao segura. Cookies de medicao e publicidade so sao ativados apos seu aceite no aviso de cookies.</Policy><Policy title="Compartilhamento">Podemos utilizar provedores de infraestrutura, autenticacao e pagamento estritamente para viabilizar o servico. Nao vendemos dados pessoais.</Policy><Policy title="Seus direitos">Voce pode solicitar acesso, correcao ou exclusao de seus dados. A exclusao pode ser iniciada na pagina Configuracoes. Registros que precisem ser mantidos por obrigacao legal ou seguranca poderao ser retidos de forma limitada.</Policy><Policy title="Contato">Para duvidas sobre privacidade, entre em contato pelo canal de suporte disponivel dentro da plataforma.</Policy></div></article></main>
}

function Policy({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="text-xl font-bold text-white">{title}</h2><p className="mt-2 text-sm text-slate-400">{children}</p></section> }